#autogenerated
# Be sure to restart your server when you modify this file.

# Your secret key for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
Remixer::Application.config.secret_token = 'a0b1bfb551bf24b8facd1e20dc5fbe5a08302b86a0ac88c07297e76c6f181a3c4cb5c58f78b3a552fc1485f0b6d1cbc308d64e6bbe89a4027ae1e92de420155c'
